### ISSUE TITLE
Unable to deserialize xml report due to non-standard date format

### ISSUE THREAD

**Issue by pklgn** [spekt/nunit.testlogger#105]
I use the nunit spekt logger to generate a report on my unit tests. In order to read this report, I use the `XmlSerilizer`'s deserialization capabilities in C#. Unfortunately, the date format in which the logger saves date is not standard (not follows ISO8601). The date is separated by an additional space, which makes it impossible to read the date through the `XmlSerilizer` (due to [XML format](https://www.w3.org/TR/xmlschema-2/#dateTime)) and forces you to write additional logic in the code for the correct parsing of the `Datetime` XML attribute. Is there any way to fix this, or at least find out the reason why it was decided to write the date in a non-standard format like in the line below:
https://github.com/spekt/nunit.testlogger/blob/1856e1fc4acd4383585b3484f2cf6df4374b12f3/src/NUnit.Xml.TestLogger/NUnitXmlSerializer.cs#L19

Let me show an example:
```
            <test-suite type="TestSuite" name="UnitTests" fullname="Example.UnitTests" total="42" passed="42" failed="0"
                        inconclusive="0" skipped="0" result="Passed" start-time="2024-04-21T19:37:28Z"
                        end-time="2024-04-21T 19:37:36Z">
```
If I manually change `start-time` value from `2024-04-21T 19:37:28Z`, which is written by logger, to `2024-04-21T19:37:28Z`, then I will have no error with `start-time`, but I will have an error with `end-time`
```
System.FormatException
The string '2024-04-17T 19:37:36Z' is not a valid AllXsd value.
```

**Comment by codito** [comment]
@pklgn this is a bug, we should follow UTC standard format. Would you like to create a fix PR?

**Comment by pklgn** [comment]
@codito I will try to create a PR within a few days.
