### ISSUE TITLE
appveyor.yml not included in repository

### ISSUE THREAD

**Issue by ngbrown** [spekt/nunit.testlogger#11]
To aid in development, it would be helpful if the `appveyor.yml` file was exported from the [currently build settings](https://ci.appveyor.com/project/Faizan2304/loggerextensions/settings/yaml) and saved into the repository.

If the yml file includes  api keys that need to be kept secret, then [encrypt them](https://www.appveyor.com/docs/how-to/secure-files/#decrypting-files-during-an-appveyor-build).

**Comment by codito** [comment]
We have the travis and appveyor files in repo now.
