### ISSUE TITLE
NunitXml.TestLogger not recognized with --logger:nunit

### ISSUE THREAD

**Issue by mcblair** [spekt/nunit.testlogger#23]
1. Added NunitXml.TestLogger to dotnet SDK based Test project via Visual Studio nuget package manager.
2. Ran `dotnet test --test-adapter-path:. --logger:nunit`
3. Output:
`Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'nunit'.`

**Comment by mcblair** [comment]
I managed to consume NunitXml.TestLogger by using `nuget.exe` to install the package directly to the project directory and assigning `--test-adapter-path` to dir `NunitXml.TestLogger.1.1.0`.

Is this the intended setup? This is what the test csproj looks like:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.0;net461</TargetFrameworks>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>   
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="2.0.1" />
    <PackageReference Include="NetEscapades.Configuration.Yaml" Version="1.3.1" />
    <PackageReference Include="nunit" Version="3.10.1" />
    <PackageReference Include="NunitXml.TestLogger" Version="1.1.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.10.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.7.0" />
  </ItemGroup>

</Project>
```

**Comment by mcblair** [comment]
I have been able to pinpoint what is causing issues.

`dotnet test --no-build --no-restore --test-adapter-path:src/NunitXml.TestLogger.1.1.0 --logger:nunit;LogFilePath=TestResultsCore.xml`

It doesn't appear to be compatible with --no-build --no-restore.

**Comment by codito** [comment]
The logger assemblies are copied to output directory of project in build step (via https://github.com/Faizan2304/LoggerExtensions/blob/master/nuspec/NunitXml.TestLogger.props). I think this step didn't run with `--no-build`.

Is the intention to run `dotnet build` first and then `dotnet test --no-build`? It should work in this scenario ideally since the `*.props` file should have been triggered with `dotnet build` itself.

**Comment by codito** [comment]
Re https://github.com/Faizan2304/LoggerExtensions/issues/23#issuecomment-388862827
> Is this the intended setup?

The test project csproj looks right. It should contain a reference to logger package.

**Comment by codito** [comment]
Thanks for sharing more context.

Can you share the logs from below step? Let's see if mono's msbuild includes the logger nuget package props files in the build process.
```
2. msbuild /t:Build /v:diag > log.txt
```

**Comment by bchavez** [comment]
I encountered the same problem.
```
Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'nunit'
```
Here's how I fixed the issue:
* Completely remove any direct calls to "MSBuild" via command-line from my build scripts and just stick to using `dotnet build` for all .NET Core/Standard builds.
* Also, deleted all `\bin` and `\obj` in all project folders before invoking `dotnet test` again. 
   * Issues can crop up if your migrating an old CSPROJ projects (using .NET Full Framework) to the new CSPROJ format. MSBuild can leave old `deps` and `obj` files that can confuse the heck out of `dotnet`.

Now everything works:
```
dotnet test --test-adapter-path:. --logger:"nunit;LogFilePath=test-result.xml"
Build started, please wait...
Build completed.

Test run for _____\bin\Debug\netcoreapp
Microsoft (R) Test Execution Command Line Tool Version 15.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Results File: _____\test-result.xml

Total tests: 62. Passed: 45. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.3485 Seconds
```

:chocolate_bar: :cookie: :lollipop: [**Ronald Jenkees - Stay Crunchy**](https://www.youtube.com/watch?v=GeIAXlwVlZc)

**Comment by codito** [comment]
Closing old issue.
