### ISSUE TITLE
Upgrade to NETStandard 2.0 needed to use System.Xml.XPath.XmlDocument

### ISSUE THREAD

**Issue by mcblair** [spekt/nunit.testlogger#26]
https://github.com/dotnet/corefx/pull/18368

Using latest `System.Xml.XPath.XmlDocument` should resolve any issues running `dotnet test -f net461 --test-adapter-path:. --logger:nunit;LogFilePath=TestResults461.xml` and seeing FileNotFound for `System.Xml.XPath.XmlDocument.dll`.

**Comment by codito** [comment]
Thanks for reporting this, will try to reproduce it.

**Comment by codito** [comment]
Closing old issue.
