### ISSUE TITLE
Output is not accepted by Sonarqube analysis tool.

### ISSUE THREAD

**Issue by da9l** [spekt/nunit.testlogger#31]
Use case: We are running sonarqube to analyze and store test results, code coverage etc. In order to do that we need to import the test results into sonarqube. 

The test results from NUnitXml.TestLogger is however rejected by sonarqube. I don't know where the problem is; on this side or in sonarqube but if it easily can be addressed here... 

```
[11:01:17][Step 9/13] ERROR: Error during SonarQube Scanner execution
[11:01:17][Step 9/13] ERROR: Missing attribute "inconclusive" in element <test-run> in D:\a02\work\ca3eccab7cb54ef1\NUnitResults.xml at line 2
[11:01:17][Step 9/13] ERROR: 
[11:01:17][Step 9/13] The SonarQube Scanner did not complete successfully
[11:01:17][Step 9/13] 11:01:18.839  Creating a summary markdown file...
[11:01:17][Step 9/13] 11:01:18.845  Post-processing failed. Exit code: 1

```

**Comment by codito** [comment]
@da9l thanks for reporting the issue! This is an issue on the logger side. I guess Sonarqube requires the attribute strictly and fails.

Problem: the test run (`dotnet test`) reports both `Inconclusive` and `[ExplicitTest]` with `TestOutcome.None`. And `Ignored` tests are reported as `TestOutcome.Skipped`. Today we club both `TestOutcome.None` and `TestOutcome.Skipped` under the `skipped` count.

There are two possible fixes I can think of:
1. Emit  `inconclusive=0` attribute for this xml report. Obviously incorrect, but also in a way explicit that the report can't find inconclusive tests to present in xml.
2. Emit an actual `inconclusive` attribute count which includes both `Inconclusive` and `[ExplicitTest]` counts. Again incorrect when user has both kinds of tests. But may be correct for most users who don't use `ExplicitTest` feature.

I am tending towards option (2). Thoughts?

**Comment by codito** [comment]
Fix available in `v2.1.15` in pre-release feed https://www.myget.org/feed/spekt/package/nuget/NunitXml.TestLogger

**Comment by da9l** [comment]
Nice! I will try it out! Thanks!

Den mån 10 sep. 2018 02:06Arun Mahapatra <notifications@github.com> skrev:

**Comment by da9l** [comment]
I can report that our version of sonarqube (6.5 (build 27846)) is very happy with the new format. Thanks again!

**Comment by codito** [comment]
@da9l glad to hear that!
