### ISSUE TITLE
TestLogger is not outputing the properties/traits for the test

### ISSUE THREAD

**Issue by aelking** [spekt/nunit.testlogger#39]
There are no Traits/Categories/Properties added to the results of the output.

We use these to decorate our tests and relate them back to the test cases within out work management system.

Not having those output means we cannot do that.

`<test-case id="0-1003" name="Inconclusive1" fullname="Test.DotNetFramework.FourPointSeven.Class1.Inconclusive1" methodname="Inconclusive1" classname="Test.DotNetFramework.FourPointSeven.Class1" runstate="Runnable" seed="5321278" result="Inconclusive" start-time="2018-11-15 09:29:33Z" end-time="2018-11-15 09:29:33Z" duration="0.004244" asserts="0">
              <properties>
                <property name="Category" value="I:AKP#15" />
              </properties>
            </test-case>`

**Comment by codito** [comment]
@aelking thanks for reporting this issue. Will look into it.

**Comment by aelking** [comment]
I will look at it right now.

**Comment by aelking** [comment]
So it is outputting properties, but not Categories.
It looks like they are stored in a diffrent property to the other traits, which is really annoying.

**Comment by aelking** [comment]
The fixes didn't add the category to the output, so I created pull request #41 that deals with other properties, such as NUnit.TestCategory

**Comment by codito** [comment]
@aelking thanks for fixing this. Merged #41 to master.

**Comment by codito** [comment]
@aelking we have a PR out for fixing duplicate properties in https://github.com/spekt/nunit.testlogger/pull/43, please take a look. Are you aware if there are any other properties like `NUnit.TestCategory` which don't show up in `Traits` collection by default?

**Comment by aelking** [comment]
I am not aware of any other issues.

I reviewed the code a couple of days ago and it looked fine. will have to wait for a build to really check it.

**Comment by aelking** [comment]
Just tried it and it is working with what I have.
