### ISSUE TITLE
NUnit test inside class object with TextFixture attribute is not extract from trx to xml

### ISSUE THREAD

**Issue by hackzai** [spekt/nunit.testlogger#44]
Hi,

I used a lot of TestFixture attribute (https://nunit.org/docs/2.5.4/testFixture.html) in my NUnit test class object. But notice all the NUnit test result from those with TestFixture attribute is not include into the final converted ml file/

**Comment by hackzai** [comment]
Or I need to upgrade my NUnit test to use the [TestFixtureData ](https://github.com/nunit/docs/wiki/TestFixtureData) instead of theTestFixture?

**Comment by codito** [comment]
@hackzai thanks for reporting this issue. In general, `TestFixture` attributes are captured by this test logger.

Can you share some sample test code to reproduce this issue? Are you already using `2.1.17` version of https://www.nuget.org/packages/NunitXml.TestLogger/?

**Comment by hackzai** [comment]
@codito Yes, I am using the 2.1.17 version and I will create a sample project to replicate the problem, and will share with you when it ready.

**Comment by jaydeept** [comment]
> Or I need to upgrade my NUnit test to use the [TestFixtureData ](https://github.com/nunit/docs/wiki/TestFixtureData) instead of theTestFixture?

With TestFixtureData as well, it's not working. Basically TestFixture isn't working well.

**Comment by Siphonophora** [comment]
@codito This should be the same issue with TryParseName that i dealt with in the Junit logger and it looks like the xunit and appveyor loggers would have the same issue as well. Presumably we could resolve it by dropping in the code I added to the other logger. I'm happy to do that, but given how much code all four of the loggers share, how about splitting the logger class into two classes or two partial classes, so all the code that should be identical for the loggers is in one place?

**Comment by codito** [comment]
@Siphonophora please feel free to refactor. One approach could be to create `TestCaseExtensions.cs` file and add `GetTestCaseName` as an extension method. This will also help us add unit tests for the name parser.

It seems to apply to nunit logger. Does xunit also allow `(` chars in test name?

**Comment by codito** [comment]
Fix available at https://www.myget.org/feed/spekt/package/nuget/NunitXml.TestLogger build `2.1.52`
