### ISSUE TITLE
The result file is bit different compared to .Net Framework one generated by NUnit Console.

### ISSUE THREAD

**Issue by jaydeept** [spekt/nunit.testlogger#45]
I am using NunitXml.TestLogger package to get the result file and using dotnet vstest to generate it. I am seeing one discrepancy here, the generated result file has duplicate test-suite name because of which one of my logic is failing. Here is the use case:
I have test case suite which has few test cases let's say: 113, Now in same suite I have another suite which contains around 120 test cases. Now previously with NUnit Console, it used to put this sub-suite under main suite only but now suite name is getting repeated twice due to which I am seeing same suite name twice in generated output XML file.

**Comment by codito** [comment]
@jaydeept thanks for reporting the issue! Would you mind sharing a sample test project to demonstrate the issue?

**Comment by jaydeept** [comment]
Hi @codito ,

Sorry I won't be able to share code due to some norms but closing this issue as I have modified logic in script to incorporate the .Net Core Test result file.
