### ISSUE TITLE
Respect ResultsDirectory

### ISSUE THREAD

**Issue by Roemer** [spekt/nunit.testlogger#46]
The default logger respects the `results-directory` path and the `LogFileName` parameter in the `logger`.
The `nunit.testlogger` uses the `LogFilePath` which is relative to the `csproj` file of the test. Would be great if the default behavior could be added as well.

So for example:
```
dotnet test "./src/Test/Test.csproj" --logger "nunit;LogFileName=tests-unit-results.xml"  --results-directory "./artifacts"
```
Would place the result file `tests-unit-results.xml` inside the `artifacts` directory.

**Comment by ashishdawale20** [comment]
@codito 
Created PR for this change, tested below scenarios:
1. dotnet test --test-adapter-path:. --logger:nunit
 --> Test results are generated in the TestResults directory relative to the test.csproj

2. dotnet test --test-adapter-path:. --logger:"nunit;LogFilePath=test-result.xml"
--> test-result.xml is generated in the same directory as test.csproj.

3. dotnet test "./src/Test/Test.csproj" --logger "nunit;LogFileName=tests-unit-results.xml"  --results-directory "./artifacts"
--> tests-unit-results.xml is generaed inside the artifacts directory.

**Comment by codito** [comment]
Fixed with https://github.com/spekt/nunit.testlogger/commit/458a0f7ad15668382bba629f35f3fa056731057f
