### ISSUE TITLE
Enhancement: Circle Ci logger?

### ISSUE THREAD

**Issue by on3al** [spekt/nunit.testlogger#47]
Circle Ci seems to require unit test results to be in Junit format
https://circleci.com/docs/2.0/configuration-reference/#store_test_results

I've seen a project for converting nunit 3 to junit using an xslt transform
https://github.com/nunit/nunit-transforms/blob/master/nunit3-junit/nunit3-junit.xslt

Would an additional logger for logging junit style output be something worth considering? All the popular js frameworks output in Junit format, so most of the popular CI platforms support it.

This project is the only thing I've been able to get working in a Circle CI pipeline, and I'de like to help creating a new logger to export to junit xml but I'm not quite sure where to start. Would it make more sense as an option to the nunit logger, or as a seperate logger? I see there is an appveyor logger already so maybe a Circle Ci Logger?

**Comment by stemann** [comment]
This is also needed for GitLab CI: https://docs.gitlab.com/ce/ci/junit_test_reports.html

**Comment by codito** [comment]
@on3al thanks for the idea and volunteering to help out! Given popularity and interop of junit xml, it is definitely worth considering. We can make it a separate logger (say junit.testlogger).

Since you already have the nunit3-junit xslt, suggest to start with a fork of nunit.testlogger and modify the logic where it emits the xml elements.
E.g. [test-case](https://github.com/spekt/nunit.testlogger/blob/master/src/NUnit.Xml.TestLogger/NUnitXmlTestLogger.cs#L297) or [test-suite](https://github.com/spekt/nunit.testlogger/blob/master/src/NUnit.Xml.TestLogger/NUnitXmlTestLogger.cs#L173)

Happy to help if you face any issues or have any questions on the logger APIs/infrastructure. Please keep us posted, once we have the changes working locally, we can move it to a separate repo.

**Comment by on3al** [comment]
For anyone else looking for a solution until there is junit logger I'm successfully  using the xunit logger https://github.com/spekt/xunit.testlogger
and converting the results  to junit using https://github.com/gabrielweyer/xunit-to-junit

**Comment by gabrielweyer** [comment]
@on3al I've never heard of `Spekt` before. I'm glad you found my project useful.

**Comment by Siphonophora** [comment]
@codito I saw this thread and was facing the same problem as on3al. In my case, its GitLab CI that wants junit formatted results. I went ahead and made a junit version. There is still cleanup to be done, but all the new tests are passing and testing I have done with GitLab looks good as well. 

Let me know if we can look at pulling this into Spekt. I'm happy to make adjustments needed to do that. 

https://github.com/Siphonophora/junit.testlogger

**Comment by codito** [comment]
@Siphonophora glad to see the new logger! We can pull it into spekt.

Do you want me to fork https://github.com/Siphonophora/junit.testlogger into spekt and add you as an admin to new repo? Or would you prefer to transfer the repo into spekt org (docs for this are [here](https://help.github.com/en/articles/transferring-a-repository)?

**Comment by Siphonophora** [comment]
@codito Go ahead and fork my repo. All the tests are passing and it seems to cover my use case without issue. We need to setup the travis and appveyor links, and probably need to decide about version numbers. I haven't changed any of that since forking from this repo.

**Comment by codito** [comment]
Here's the new repo: https://github.com/spekt/junit.testlogger. Added CI builds to the repo.

Pre-release nuget packages are now available at https://www.myget.org/feed/spekt/package/nuget/JunitXml.TestLogger. Please test it out. We can do a nuget release if everything looks good on prerelease packages.

**Comment by codito** [comment]
We have released https://www.nuget.org/packages/JUnitXml.TestLogger. Thanks @Siphonophora for the great work!

Please open new issue at https://github.com/spekt/junit.testlogger if you find something broken.
