### ISSUE TITLE
Few test cases aren't getting added in report file for .Net Core 2.2

### ISSUE THREAD

**Issue by jaydeept** [spekt/nunit.testlogger#48]
Hello,

I am executing the `NUnit` test cases using below command in `.Net Core 2.2`:

> dotnet vstest UnitTests.dll /logger:'nunit;LogFilePath=reports/TestResult-Unit

I am seeing that all test cases are getting executed but in report file few test case's results aren't getting added. I narrowed down the issue and found that the test case class which are having `TestFixture` at class level, aren't getting added in report file. For example,

```
namespace DBTests
{
    [TestFixture(RunOn.Oracle)]
    [TestFixture(RunOn.SqlServer)]
    [Parallelizable]
    public class CreateObjectsTests 
    {
        [Test]
        public void Test1()
        {
            ............
        }
    }
}
```

where `RunOn` is `enum`.

I am using 2.1.36 version.

P.S.
These test cases are working fine in `.Net Framework` and are getting recorded properly in report file, using `nunit3-console.exe`.

**Comment by jaydeept** [comment]
I believe this is similar to #44

**Comment by vipetrul** [comment]
I encountered the same problem as well. Have you looked into underlying issue?

**Comment by codito** [comment]
Fixed with https://github.com/spekt/nunit.testlogger/commit/e00a237277b325db1a8625df05e21001e13d4794

**Comment by codito** [comment]
Fix available at https://www.myget.org/feed/spekt/package/nuget/NunitXml.TestLogger build `2.1.52`
