### ISSUE TITLE
Description and topics outdated

### ISSUE THREAD

**Issue by milbrandt** [spekt/nunit.testlogger#51]
Description "Loggers for vstest platform (xunit, nunit and appveyor)." and Topics "vstest nunit logger test-reporting nuget dotnet dotnet-test " seems to be outdated as Xunit and appveyor testloggers moved to own repos (as mentioned in your `Readme.md`):
https://github.com/spekt/xunit.testlogger
https://github.com/spekt/appveyor.testlogger

**Comment by codito** [comment]
thanks @milbrandt! Updated description.
