### ISSUE TITLE
Aggregate results from multiple assemblies

### ISSUE THREAD

**Issue by otherdave** [spekt/nunit.testlogger#59]
Hi! Thanks for the work on this project!

I currently have a solution with two Test projects. When I run the example `dotnet test MySolution.sln ...` and specify the LogFilepath, I get a single results file. It looks like the last Test Assembly to be tested overwrites the previous ones. 

I want a single results file that's the aggregate of my test run so I can publish a single results file through Jenkins. Is this possible?

(I'm also looking for a Jenkins solution to publishing multiple TestResults.xml files)

**Comment by otherdave** [comment]
For what it's worth, I did find a way to publish multiple results.xml files to Jenkins, so this issue isn't that important. However, I'm still curious if it's possible to output a single results file.

**Comment by Siphonophora** [comment]
@otherdave 

First, I wanted to mention that if you use `{assembly}` in the command line, the logger will produce unique file names per csproj file. 
```
> dotnet test --test-adapter-path:. --logger:"nunit;LogFilePath={assembly}-test-result.xml"
```

Second, I believe we are constrained by the lifecycle that the test sdk uses for loggers. We are responding to events and TestRunCompleteHandler, for example, is called once per csproj file. 

https://github.com/spekt/nunit.testlogger/blob/master/src/NUnit.Xml.TestLogger/NUnitXmlTestLogger.cs

**Comment by rob-spoor** [comment]
I addition to what @Siphonophora said, you can use `{framework}` instead of `{assembly}` to get a file per framework. Note that you should add a relative path to put the files in folder `TestResults`. For instance:

    dotnet test --logger:"nunit;LogFilePath=TestResults\TestResult-{framework}.xml"

Even with multiple projects in your solution, each project gets a file like `TestResults\TestResult-NETCoreApp31.xml`.

**Comment by codito** [comment]
Closing this since we have capability to publish assembly/framework specific result files. We can revisit if this is still a blocker.

**Comment by richardrflores** [comment]
Hi,

Using the `{framework}` to generate a file per framework does not work. It does not aggregate the results for a solution with multiple test projects. 

I have the packages below in each test project and I'm using this command to execute the tests `dotnet test --logger:"nunit;LogFilePath=..\WeatherForecast\bin\Debug\{assembly}\TestResults\TestResult-{assembly}.xml"`

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
        <PackageReference Include="NUnit" Version="3.13.1" />
        <PackageReference Include="NUnit.Console" Version="3.12.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="3.17.0" />
        <PackageReference Include="coverlet.collector" Version="3.0.2" />
        <PackageReference Include="NunitXml.TestLogger" Version="3.0.113" />
  </ItemGroup>

This produces an xml file in each project, and also produces an xml file for the framework as specified in the LogFilePath, but the results are not aggregated. It appears to overwrite the results from the last run test project.

Am I missing something?

Appreciate any help...thanks!

**Comment by Siphonophora** [comment]
Hi, I saw your other comments over the weekend and have been thinking about it a little. What we can do during logging is constrained by how our library is called, which is once per test project. That means we produce one file per test project, even though the logging xml schema would support combining all of the data into one file.

Combining the log data across multiple libraries would need to be another step in your pipeline that runs after all testing is complete. Do you have a CICD workflow that can only handle one file?

And yes, it will overwrite the previous file, so we recommend using the `framework` and `assembly` tokens to prevent this when saving multiple files to a single folder.

**Comment by richardrflores** [comment]
Thanks for the response @Siphonophora. Not sure why, but the `framework` nor the `assembly` tokens worked for me as described. Apologies if I wasn't clear about that in my question. 

In any case, I found a solution. I stumbled across the `dotnet vstest` command which allows you to target multiple assemblies and aggregate the results. This worked, but I found out [here](https://github.com/dotnet/docs/issues/14786) that `dotnet vstest` has been superseded by `dotnet test` so this will work the same: `dotnet test .\WeatherForecastTests\bin\Debug\netcoreapp3.1\WeatherForecastTests.dll .\MoreTests\bin\Debug\netcoreapp3.1\MoreTests.dll --logger:"nunit;LogFileName=TestResult.xml"`

A few additional observations:
1. This might be obvious, but you still need to have `<PackageReference Include="NunitXml.TestLogger" Version="3.0.113" />` in your test project.
2. If you don't specify a result directory, the result file will be generated in the directory where the `dotnet test` command was executed.  If you specify a directory in the `LogFileName` argument, then the result file is generated in a directory called `TestResult\<your-specified-directory-name>` For more granular control, you can use the `--results-directory` switch to specify a path or directory; the directory will be created if it does not exist. See [dotnet test docs](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test) for more info.
3. When targeting multiple assemblies with `dotnet test`, no test result files are generated in the source test projects. 

Anyway, I hope this helps anyone else needing to aggregate test results from multiple test projects.

**Comment by Siphonophora** [comment]
@richardrflores Thanks for adding this. I hadn't known you could get `dotnet test` to run multiple test libraries at once.
