### ISSUE TITLE
test case description is not add to the report 

### ISSUE THREAD

**Issue by parthsarathiravi** [spekt/nunit.testlogger#69]
in the below code I add a Description for the test 
`

       [Test]
        [Description("Passing test description")]
        public void IsPrime_InputIs1_ReturnFalse()
        {
            var result = _primeService.IsPrime(1);
            Assert.IsFalse(result, "1 should not be prime");
        }
        #region Sample_TestCode
        [TestCase(-1, TestName = "test with negative")]
        [TestCase(0, Description= "when 0 pass it should work")]
        [TestCase(1)]
        public void IsPrime_ValuesLessThan2_ReturnFalse(int value)
        {
            var result = _primeService.IsPrime(value);

            Assert.IsFalse(result, $"{value} should not be prime");
        }
        #endregion
`

in xml report, the description is not added by Testlogger.
`<test-case name="IsPrime_InputIs1_ReturnFalse" fullname="Prime.UnitTests.Services.TPrimeService_IsPrimeShouldests.IsPrime_InputIs1_ReturnFalse" description="Mock Test #1" result="Passed" duration="0.007155" asserts="0" />
      <test-case name="test with negative" fullname="Prime.UnitTests.Services.TPrimeService_IsPrimeShouldests.test with negative" result="Passed" duration="0.000192" asserts="0" />
      <test-case name="IsPrime_ValuesLessThan2_ReturnFalse(0)" fullname="Prime.UnitTests.Services.TPrimeService_IsPrimeShouldests.IsPrime_ValuesLessThan2_ReturnFalse" result="Passed" duration="3.8E-05" asserts="0" />
      <test-case name="IsPrime_ValuesLessThan2_ReturnFalse(1)" fullname="Prime.UnitTests.Services.TPrimeService_IsPrimeShouldests.IsPrime_ValuesLessThan2_ReturnFalse" result="Passed" duration="3.1E-05" asserts="0" />`

**Comment by Siphonophora** [comment]
@parthsarathiravi There isn't a description attribute on a test case. https://docs.nunit.org/articles/nunit/technical-notes/usage/Test-Result-XML-Format.html#test-case Maybe it could be a property, but I'm not sure about the level of effort to do so.

**Comment by codito** [comment]
Tracked with https://github.com/nunit/nunit3-vs-adapter/issues/847

**Comment by OsirisTerje** [comment]
@codito @Siphonophora The output of some internal properties are off by default in the adapter, this includes the Description.   In order to get them out you can set the runsettings property ShowInternalProperties, like 
```
dotnet test GherkinSuites\GherkinSuites.csproj --no-build --logger:nunit;LogFileName=TestResults.xml --logger:trx;LogFileName=TestResult.trx -- NUnit.ShowInternalProperties=true
```
(Note the space between the ```--``` and the property)
or set it in a .runsettings file and use the ```--settings .runsettings``` option.  

Note that you also can get the nunit logger output from the adapter by setting the property ```NUnit.TestOutputXml=somefoldername```

This folder is relative to the binary location though. This output should be the same as what one get from the nunit.console logger, since it is the same code that is invoked. 
Example output from https://github.com/nunit/nunit3-vs-adapter/issues/847 :
```
<test-case id="0-1001" name="Test1" fullname="Issue847.Tests.Test1" methodname="Test1" classname="Issue847.Tests" runstate="Runnable" seed="1322471594" result="Passed" start-time="2021-05-22T14:44:40.0192547Z" end-time="2021-05-22T14:44:49.6630803Z" duration="9.643983" asserts="0">
          <properties>
            <property name="Category" value="Whatever" />
            <property name="Description" value="some text here" />
          </properties>
        </test-case>
```
