### ISSUE TITLE
The nunit3 XML report of Specflow tests cannot be processed by Pickles 

### ISSUE THREAD

**Issue by WenningQiu** [spekt/nunit.testlogger#71]
Although the Specflow tests that I run on .NET Core 3.1 using command "dotnet test --logger:nunit" all pass, the tests are displayed as "inconclusive" on the HTML reports produced by Pickles. Pickles has no trouble processing the nunit3 XML reports generated by NUnit3-Console.exe. 

The root cause is that NUnit3-Console.exe generates \<properties> element on \<test-suite> and \<test-case> tags based on the attributes on the test fixture and test cases, which is not done by NunitXml.TestLogger. Below is a snippet from NUnit3-Console.exe report and the corresponding test class:

![image](https://user-images.githubusercontent.com/4291622/95480718-d7a75200-0951-11eb-9e2d-1eb4ba885c99.png)
![image](https://user-images.githubusercontent.com/4291622/95483246-9d8b7f80-0954-11eb-967b-e759365fddb4.png)

Pickles functionality depends on the presence of "Description" \<property> tag.

**Comment by WenningQiu** [comment]
"dotnet test" appears to have captured "NUnit.Framework.CategoryAttribute" on test cases and passed on the category values to the log adapter as traits and NunitXml.TestLogger is able to generate \<property> elements with name="Category" attribute. 

The following are the gaps:

1. "dotnet test" needs to also  capture "NUnit.Framework.DescriptionAttribute" on test cases and pass on information to the log adapter.
1. "dotnet test" needs to capture both attributes on the test fixture class and pass on the information to the log adapter.
1. NunitXml.TestLogger needs to generate \<properties> tag with "Description" and "Category" properties on the \<test-suite> element with type="TestFixture".
1. NUnitXml.TestLogger needs to generate \<property> tag for "Description".

**Comment by WenningQiu** [comment]
One more gap is SpecFlow scenario with "examples" has each "example" as flat \<test-case> element directly under type "TestFixture" \<test-suite> element. They should instead be grouped with \<test-suite> element of type "ParametizedMethod" as below:
![image](https://user-images.githubusercontent.com/4291622/95703693-f426e100-0c14-11eb-8acb-9ab343c2c4fc.png)

**Comment by codito** [comment]
Created https://github.com/nunit/nunit3-vs-adapter/issues/847 to track the missing properties like `Description` in nunit adapter.

**Comment by OsirisTerje** [comment]
@codito @WenningQiu Description property can be enabled in the adapter, see https://github.com/spekt/nunit.testlogger/issues/69#issuecomment-846443647.  Also, to get the same format as for the NUnit.Console, use the NUnit.TestOutputXml property, as shown in https://github.com/spekt/nunit.testlogger/issues/69#issuecomment-846443647

**Comment by codito** [comment]
We've added both the adapter configuration to documentation.

Keeping this issue around to investigate if we should support two additional `test-suite` types in this logger: `ParameterizedMethod` and `ParameterizedFixture`.
