### ISSUE TITLE
Xunit Theories are reported without their input data

### ISSUE THREAD

**Issue by sl-slaing** [spekt/nunit.testlogger#72]
If a theory is created with inline, or other data sources, shows in the report with the method name only.

As such it is impossible to determine the scenarios that have been tested, and in the case of a failure which inputs were part of the test.

NUnit XML format supports the reporting of this data, is it possible to report this in the XML via this library? Similar to the output Resharper shows in its unit test session window?

Example reproduction:

```
[InlineData("foo")]
[InlineData(null)]
public void MyTheory(string input) {
  Assert.NotNull(input);
}
```

This is reported as:
- MyTheory - pass
- MyTheory - fail

Ideally it would be reported as (or something equivalent to):
- MyTheory(input: "foo") - pass
- MyTheory(input: null) - fail

**Comment by codito** [comment]
With `3.0.127` of NUnitXml.TestLogger, the reporting is as expected. Closing the issue, please reopen if needed.

```xml
<test-case name="trial.UnitTest1.MyTheory(input: &quot;foo&quot;)" fullname="trial.UnitTest1.MyTheory(input: &quot;foo&quot;)" methodname="MyTheory(input: &quot;foo&quot;)" classname="UnitTest1" result="Passed" start-time="2023-07-05T 06:18:53Z" end-time="2023-07-05T 06:18:53Z" duration="0.0027172" asserts="0" />
<test-case name="trial.UnitTest1.MyTheory(input: null)" fullname="trial.UnitTest1.MyTheory(input: null)" methodname="MyTheory(input: null)" classname="UnitTest1" result="Failed" start-time="2023-07-05T 06:18:53Z" end-time="2023-07-05T 06:18:53Z" duration="0.0009457" asserts="0">
```
