### ISSUE TITLE
Existing test result files are not cleared

### ISSUE THREAD

**Issue by tkohlmeier** [spekt/nunit.testlogger#76]
When running a test with an existing test result file, the old content is not cleared. The new content is written into the old file, overwriting characters that have been there before.

Example:

Old file content:

    example
    content
    bla

New results:

    new example
    test

This results in:

    new example
    testent
    bla

Not sure if this is a problem of nunit.testlogger or .NET Core.

**Comment by codito** [comment]
@tkohlmeier this appears to be a regression. I will create a fix shortly.

**Comment by codito** [comment]
Pushed a fix to nuget: v3.0.97. Please try it out. Thank you for reporting this issue.

**Comment by tkohlmeier** [comment]
I can confirm that the issue is fixed with the current version. Thanks for fixing this so quickly!
