### ISSUE TITLE
Test cases not reported with the seed value

### ISSUE THREAD

**Issue by qubitz** [spekt/nunit.testlogger#78]
I started using NUnit's `Randomizer` class to generate random test data, but I need to make sure that I can reproduce test results if a test fails. That's when I started looking into how to output NUnit's xml test results with `dotnet test` and came across this repository 🥳. However it seems that the seed value is never output compared to older NUnit xml test results.

Expected:
```xml
<test-case name="GeneratesValidSettings" seed="83948563" fullname="Some.Tests.GeneratesValidSettings" methodname="GeneratesValidSettings" classname="SettingsTests" result="Passed" start-time="2021-04-07T 01:04:44Z" end-time="2021-04-07T 01:04:44Z" duration="0.109629" asserts="0" />
```
Actual
```xml
<test-case name="GeneratesValidSettings" <!--missing seed--> fullname="Some.Tests.GeneratesValidSettings" methodname="GeneratesValidSettings" classname="SettingsTests" result="Passed" start-time="2021-04-07T 01:04:44Z" end-time="2021-04-07T 01:04:44Z" duration="0.109629" asserts="0" />
```
This seed attribute is referenced in the [NUnit docs](https://docs.nunit.org/articles/nunit/writing-tests/TestContext.html#random) and in this [NUnit issue](https://github.com/nunit/nunit/issues/1461).

Looking into the issue more thoroughly, [this method](https://github.com/spekt/nunit.testlogger/blob/516893f457acb4e96f2ccaffac37756c932a16c4/src/NUnit.Xml.TestLogger/NUnitXmlSerializer.cs#L235) seems like where the seed value would be serialized. However, `TestResultInfo` only has access to data held within VSTest's `TestCase` which has no "seed" member. Is it possible that seed data from NUnit could be held within `TestCase` elsewhere ([here maybe](https://github.com/microsoft/vstest/blob/561b88bb8478e9fb78d1ff043928401f862e856d/src/Microsoft.TestPlatform.ObjectModel/TestCase.cs#L189)) or do I need to look at another method of outputting NUnit's xml test results?

**Comment by codito** [comment]
@qubitz this is an interesting scenario. Unfortunately, the `seed` value is not exposed via the `TestCase` traits or properties :( 

Created https://github.com/nunit/nunit3-vs-adapter/issues/843 with an ask if adapter can support this.
