### ISSUE TITLE
'nunit' Firendly name not found when using multiple loggers

### ISSUE THREAD

**Issue by matheus-inacio** [spekt/nunit.testlogger#80]
When executing tests using nunit and junit logger, i've started facing the following message:

`Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName 'nunit'.`

Command used:

```
dotnet test
        --no-restore
        --no-build
        --test-adapter-path:.
        --logger:"nunit;LogFilePath=..\artifacts\{assembly}-nunit-result.xml;"
        --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
```

Package versions:
```
<PackageReference Include="nunit" Version="3.13.2" />
<PackageReference Include="NUnit3TestAdapter" Version="3.17.0" />
<PackageReference Include="JunitXml.TestLogger" Version="3.0.87" />
<PackageReference Include="NunitXml.TestLogger" Version="3.0.97" />
```

I can confirm that once i remove JunitXml.TestLogger or downgrade it to version `2.1.81` the command works again.

PS.: My project targets .net 5.0

**Comment by codito** [comment]
@matheus-inacio thank you for reporting this issue. We've created a new release v3.0.104 with the fix. It should be available in nuget.org in a few minutes.

**Comment by codito** [comment]
Sorry, reopening it as I am able to reproduce the issue. Digging deeper.

**Comment by codito** [comment]
I mistakenly pushed the package with older version of common TestLogger to nuget. It should be fixed now. Please try `v3.0.107`.
