### ISSUE TITLE
Create unique filename for nunit3 XML+ vstest

### ISSUE THREAD

**Issue by shalomda** [spekt/nunit.testlogger#85]
What is the way to create unique filename for nunit3 XML + vstest cli?
{assembly} or {framework} do not solve that issue

`dotnet vstest Test.dll --logger:"nunit;LogFileName=test-result.{date}.xml"`

**Comment by codito** [comment]
@shalomda thank you for the feature request. Is it an option to use shell commands? (or their equivalent in powershell)

![image](https://user-images.githubusercontent.com/28766/123530716-3ea4ab00-d71b-11eb-8fad-654ebde88721.png)

**Comment by shalomda** [comment]
Thank you, I don't success. Can you copy here your line please?

**Comment by codito** [comment]
Sure, `dotnet vstest bin/Debug/net5.0/trial.dll --logger:"nunit;LogFileName=test-result.$(date +%s).xml"`.

This command will work in linux shells. If you're on windows, please try following in Powershell:

`dotnet vstest bin/Debug/net5.0/trial.dll --logger:"nunit;LogFileName=test-result.$(Get-Date -UFormat %s).xml"`

**Comment by shalomda** [comment]
Thank you very much! Do you know what is the line for the cmd?

**Comment by shalomda** [comment]
In cmd the line created me this file name: test-result.$(date +%s).xml. The date was not generated

**Comment by codito** [comment]
Sorry, no idea about `cmd`, not an expert :( May be there's a way to use similar idea: use the `date /t` command, save output in a variable and then substitute it in the dotnet command line.

I will close this issue since this problem can be solved using modern shells.
