### ISSUE TITLE
`classname` attribute not set for "TestFixture"-type <test-suite> elements

### ISSUE THREAD

**Issue by mthjones** [spekt/nunit.testlogger#88]
From the [NUnit docs](https://docs.nunit.org/articles/nunit/technical-notes/usage/Test-Result-XML-Format.html#test-suite) for the `<test-suite>` element:

> **classname** The full name of the class (fixture) representing this test. Only present if `type` is equal to "TestFixture".

This value doesn't seem to be getting set for "TestFixture"-type suites, which breaks parsing of the results file in tools that rely on the attribute being present.

(sort of related to #87)

**Comment by codito** [comment]
Fixed with ba9e13f40570ca598d9ad9dfa58ac8497f488ebe
