### ISSUE TITLE
Logger produces test results for one project only

### ISSUE THREAD

**Issue by RusKnyaz** [spekt/nunit.testlogger#89]
It looks like if the solution contains several projects test result file will be rewritten by the last one's results.

Try the attached [Tests.zip](https://github.com/spekt/nunit.testlogger/files/7568575/Tests.zip).
1. Unzip it.
2. run 'dotnet test -l nunit -r test-results'
Observed: single TestResults.xml file with only tests from Project2
Expected: One or several files with test results for Project1, Project2, and for net462,netcoreapp3.1

**Comment by codito** [comment]
Would the assembly token help? See https://github.com/spekt/testlogger/wiki/Logger-Configuration#logfilename

**Comment by RusKnyaz** [comment]
Thank you, it works.
