### ISSUE TITLE
Missing elements in the results XML file

### ISSUE THREAD

**Issue by letaoana** [spekt/nunit.testlogger#91]
The generated results file does not have `<?xml version="1.0" encoding="UTF-8" ?>` declaration and the `<environment>` element.

**Comment by codito** [comment]
@letaoana which element is missing? Could you please share a sample repro if possible?

**Comment by letaoana** [comment]
@codito The generated results file does not have `<?xml version="1.0" encoding="UTF-8" ?>` declaration and the `<environment>` element.
