### ISSUE TITLE
Cannot use multiple Spekt loggers in parallel

### ISSUE THREAD

**Issue by Paciv** [spekt/nunit.testlogger#95]
Hello,

I can't use Nunit.XML.TestLogger and Junit.XML.TestLogger from the same test folder.

Since [N/J/X]Unit.XML.TestLogger nuget packages from Spekt all include the Spekt.TestLogger.dll dependency directly,
Different versions of the dll will be copied to the same destination folder (and one will win)
Depending on the winner dll, some logger versions will not work (some combination do work though).

I saw that the Spekt.TestLogger.dll version was the same in the JUnit and the NUnit repository.
But the NUnit.XML.TestLogger hasn't been released as a nuget package since the dependency version update.

Could you please release a nuget package with the current version of the Nunit.testlogger repository (Spekt.TestLogger 3.0.78) ?

**Comment by codito** [comment]
https://www.nuget.org/packages/NunitXml.TestLogger/3.0.127 is now available. Please try it out.
