### ISSUE TITLE
How to append screenshots to xml report ?

### ISSUE THREAD

**Issue by bheemreddy181** [spekt/nunit.testlogger#96]
Hey Team,

Is there a way for failed tests, we can append the screenshot paths to the report so that any reporting dashboards can pick them up ?

Regards
Bheem

**Comment by Siphonophora** [comment]
Hi @bheemreddy181 as you saw, this is a duplicate of #54

**Comment by bheemreddy181** [comment]
Cool sounds good. Can we update this with latest dotnet packages ?

**Comment by Siphonophora** [comment]
Are you seeing a compatibility issue? This should work with .net 7

**Comment by codito** [comment]
Duplicate of #54
