### ISSUE TITLE
Parsing error when namespace contains 0

### ISSUE THREAD

**Issue by evoAttilaK** [spekt/nunit.testlogger#99]
If the namespace where the test class is contains 0(Zero) than the following will happen:
<test-suite type="TestFixture" name="UnknownType" fullname="UnknownNamespace.UnknownType" ...>

namespace example: IT_MotorEngine.S0

And the message from the console:
Test Logger: Unable to parse one or more test names provided by your test runner. These will be logged using Namespace='UnknownNamespace', Type='UnknownType'. The entire test name will be used as the Method name. Please open a ticket so we can review this issue

An example, how to reproduce the issue: https://github.com/nunit/nunit3-vs-adapter.issues/tree/master/Issue1096

And also I attached mine.
[NUnitParseIssue.zip](https://github.com/spekt/nunit.testlogger/files/11945432/NUnitParseIssue.zip)

**Comment by codito** [comment]
This doesn't repro in the latest preview package.

You can try using it. We will cut a new release to nuget in a day or two.

```
dotnet add package NunitXml.TestLogger --version 3.1.12 --source https://www.myget.org/F/spekt/api/v3/index.json
```

**Comment by codito** [comment]
Cut a new release, please try https://www.nuget.org/packages/NunitXml.TestLogger/3.1.15
